# Generated by Django 5.2.7 on 2026-03-14 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_academies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='academy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='academy.academy'),
        ),
    ]
