# Generated by Django 5.2.7 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestreak',
            name='grace_days_allowed',
            field=models.PositiveIntegerField(default=3, help_text='Maximum banked grace days'),
        ),
        migrations.AddField(
            model_name='attendancestreak',
            name='grace_days_banked',
            field=models.PositiveIntegerField(default=0, help_text='Grace days available to use'),
        ),
    ]
