# Generated by Django 5.2.7 on 2026-03-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HadithBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['collection', 'book_number'],
            },
        ),
        migrations.CreateModel(
            name='HadithCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Collection identifier (e.g. bukhari)', unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('total_hadiths', models.PositiveIntegerField(default=0)),
                ('introduction_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='HadithChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=500)),
                ('title_ar', models.CharField(max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='sunnah.hadithbook')),
            ],
            options={
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_number', models.CharField(max_length=20)),
                ('reference_inbook', models.CharField(blank=True, max_length=100)),
                ('arabic_text', models.TextField(help_text='Amiri Font recommended')),
                ('text_en', models.TextField()),
                ('text_ur', models.TextField(blank=True)),
                ('narrator_en', models.CharField(blank=True, max_length=500)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('grade_source', models.CharField(blank=True, max_length=255)),
                ('urn', models.CharField(help_text='Unique Research Number from Sunnah.com', max_length=100, unique=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='sunnah.hadithchapter')),
            ],
            options={
                'ordering': ['chapter', 'hadith_number'],
            },
        ),
        migrations.AddField(
            model_name='hadithbook',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='sunnah.hadithcollection'),
        ),
        migrations.AlterUniqueTogether(
            name='hadithbook',
            unique_together={('collection', 'book_number')},
        ),
    ]
