# Generated by Django 5.2.7 on 2026-03-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_is_active_and_more'),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='quran.ayat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_bookmarks', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'ayat')},
            },
        ),
    ]
