# Generated by Django 5.2.7 on 2026-03-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_is_active_and_more'),
        ('lessons', '0002_hadithbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('google_meet_url', models.URLField(blank=True, null=True)),
                ('google_meet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('students', models.ManyToManyField(related_name='class_sessions', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('quran_recitation', 'Quran Recitation'), ('quran_memorization', 'Quran Memorization'), ('quran_revision', 'Quran Revision'), ('tajweed', 'Tajweed'), ('tafsir', 'Tafsir'), ('islamic_studies', 'Islamic Studies'), ('arabic_language', 'Arabic Language'), ('dua_hadith', 'Dua & Hadith')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('surah_from', models.PositiveIntegerField(blank=True, null=True)),
                ('ayat_from', models.PositiveIntegerField(blank=True, null=True)),
                ('surah_to', models.PositiveIntegerField(blank=True, null=True)),
                ('ayat_to', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1-5')),
                ('homework_given', models.BooleanField(default=False)),
                ('homework_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
