# Generated by Django 5.2.7 on 2026-03-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Ayat number within the surah')),
                ('arabic_text', models.TextField(help_text='KFGQPC Uthmanic Script')),
                ('translation_en', models.TextField(help_text='Mustafa Khattab')),
                ('translation_ur', models.TextField()),
                ('transliteration', models.TextField()),
                ('juz', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField()),
                ('sajda', models.BooleanField(default=False)),
                ('ruku', models.PositiveIntegerField()),
                ('hizb', models.PositiveIntegerField()),
                ('verse_key', models.CharField(help_text='e.g. 1:1', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['surah__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('first_surah', models.IntegerField()),
                ('first_ayat', models.IntegerField()),
                ('last_surah', models.IntegerField()),
                ('last_ayat', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Juzs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('audio_url_pattern', models.CharField(help_text='Pattern to construct audio URLs', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Surah number (1-114)', unique=True)),
                ('name_arabic', models.CharField(max_length=255)),
                ('name_english', models.CharField(max_length=255)),
                ('name_transliteration', models.CharField(max_length=255)),
                ('revelation_type', models.CharField(choices=[('Meccan', 'Meccan'), ('Medinan', 'Medinan')], max_length=20)),
                ('ayat_count', models.PositiveIntegerField()),
                ('juz_start', models.PositiveIntegerField()),
                ('page_start', models.PositiveIntegerField()),
                ('chronological_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AyatWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('arabic', models.CharField(max_length=255)),
                ('transliteration', models.CharField(max_length=255)),
                ('translation_en', models.CharField(max_length=255)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.ayat')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='ayat',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayats', to='quran.surah'),
        ),
        migrations.CreateModel(
            name='Tafsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.ayat')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ayat',
            unique_together={('surah', 'number')},
        ),
    ]
